### ISSUE TITLE
Where condition of SharingProvider is empty if the list of security identities is empty

### ISSUE THREAD

**Issue by bohrsty** [sonatra/sonatra-security#2]
As stated in [sonatra-security-bundle issue 15](https://github.com/sonatra/sonatra-security-bundle/issues/15) (comments [346948606](https://github.com/sonatra/sonatra-security-bundle/issues/15#issuecomment-346948606) and [346952527](https://github.com/sonatra/sonatra-security-bundle/issues/15#issuecomment-346952527)) the SharingProvider ignores all `IS_` Role Security Identites.

**Comment by francoispluchino** [comment]
I think I did not speak well. The bug is not what you describe, that is to say the security identities starting with `IS_` are not listed in the SQL filter. It's normal, they are not real roles. But, the bug is in the fact that there is no second validation, by checking that the list of security identities is not empty before adding this list to the condition WHERE of the SQL filter.

**Comment by francoispluchino** [comment]
Fixed by 4f6ac6a8a67510da6079ea9e7b1902c251c70144.
